# Generated by Django 5.0 on 2023-12-23 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.TextField()),
                ("location", models.CharField(max_length=255)),
                ("features", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rent_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "unit_type",
                    models.CharField(
                        choices=[
                            ("1BHK", "1BHK"),
                            ("2BHK", "2BHK"),
                            ("3BHK", "3BHK"),
                            ("4BHK", "4BHK"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="Tenant.property",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("monthly_rent_date", models.DateField()),
                ("expiry_date", models.DateField()),
                (
                    "document_proof",
                    models.FileField(blank=True, null=True, upload_to="proof/"),
                ),
                (
                    "unit",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Tenant.unit",
                    ),
                ),
            ],
        ),
    ]
